// Package config loads and validates service configuration from environment variables.
// Generated by crux dev.
package config

import "os"

// Config holds all runtime configuration for my-service.
// Values are read from environment variables at startup.
// Never log Config values — they may contain secrets.
type Config struct {
	ServiceName string
	Environment string
	Port        string
	LogLevel    string
	// Build metadata injected via ldflags.
	Commit    string
	BuildTime string
	// OTel exporter endpoint (default: localhost:4317).
	OTLPEndpoint string
}

// Load reads configuration from environment variables and returns a Config.
// Missing optional variables fall back to safe defaults.
func Load() *Config {
	return &Config{
		ServiceName:  envOr("SERVICE_NAME", "my-service"),
		Environment:  envOr("ENVIRONMENT", "development"),
		Port:         envOr("PORT", "8080"),
		LogLevel:     envOr("LOG_LEVEL", "info"),
		Commit:       os.Getenv("COMMIT"),
		BuildTime:    os.Getenv("BUILD_TIME"),
		OTLPEndpoint: envOr("OTEL_EXPORTER_OTLP_ENDPOINT", "localhost:4317"),
	}
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
