// Package tracing provides OTel middleware and HTTP client transport.
// Generated by crux dev.
package tracing

import (
	"net/http"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/propagation"
)

// Transport injects the W3C traceparent header into every outbound HTTP request.
type Transport struct {
	wrapped http.RoundTripper
}

// NewTransport returns a Transport wrapping base (nil → http.DefaultTransport).
func NewTransport(base http.RoundTripper) *Transport {
	if base == nil {
		base = http.DefaultTransport
	}
	return &Transport{wrapped: base}
}

// RoundTrip injects traceparent then delegates to the wrapped transport.
func (t *Transport) RoundTrip(req *http.Request) (*http.Response, error) {
	r := req.Clone(req.Context())
	otel.GetTextMapPropagator().Inject(r.Context(), propagation.HeaderCarrier(r.Header))
	return t.wrapped.RoundTrip(r)
}

// NewHTTPClient returns an *http.Client that injects traceparent on every request.
func NewHTTPClient(base http.RoundTripper) *http.Client {
	return &http.Client{Transport: NewTransport(base)}
}
