// Package health provides the health check registry and status types.
// Generated by crux dev.
package health

import "sync"

// Status represents the health status of a dependency.
type Status string

const (
	StatusHealthy   Status = "healthy"
	StatusDegraded  Status = "degraded"
	StatusUnhealthy Status = "unhealthy"
)

// CheckFunc is a function that reports the health of a dependency.
type CheckFunc func() Status

// Registry holds registered dependency health checks.
type Registry struct {
	mu     sync.RWMutex
	checks map[string]CheckFunc
}

// NewRegistry returns an empty Registry.
func NewRegistry() *Registry {
	return &Registry{checks: make(map[string]CheckFunc)}
}

// Register adds a named health check to the registry.
func (r *Registry) Register(name string, fn CheckFunc) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.checks[name] = fn
}

// Results returns the current status of all registered checks.
func (r *Registry) Results() map[string]Status {
	r.mu.RLock()
	defer r.mu.RUnlock()
	out := make(map[string]Status, len(r.checks))
	for name, fn := range r.checks {
		out[name] = fn()
	}
	return out
}

// Ready returns true only when every registered check reports healthy.
func (r *Registry) Ready() bool {
	for _, s := range r.Results() {
		if s != StatusHealthy {
			return false
		}
	}
	return true
}
