// Package main is the entrypoint for my-service.
// Generated by crux dev on 2026-03-18T14:28:49Z.
// Read TODO.md before writing business logic.
package main

import (
	"context"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"time"

	"github.com/gin-gonic/gin"

	"github.com/company/my-service/internal/config"
	"github.com/company/my-service/internal/domain/health"
	"github.com/company/my-service/internal/infrastructure/logging"
	"github.com/company/my-service/internal/infrastructure/shutdown"
	"github.com/company/my-service/internal/infrastructure/tracing"
	infrahttp "github.com/company/my-service/internal/presentation/http"
)

// version is injected at build time via -ldflags "-X main.version=<tag>".
var version = "dev"

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "fatal: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	cfg := config.Load()

	logger := logging.New(os.Stdout, cfg.ServiceName, cfg.Environment, version)
	log := logger.WithContext(context.Background())

	// Initialise OTel tracing — W3C traceparent is the org-wide standard.
	shutdownTracing, err := tracing.Init(context.Background(), cfg.ServiceName, version)
	if err != nil {
		return fmt.Errorf("tracing init: %w", err)
	}

	registry := health.NewRegistry()

	if cfg.Environment == "production" {
		gin.SetMode(gin.ReleaseMode)
	}

	router := infrahttp.NewRouter(infrahttp.RouterConfig{
		Logger:   log,
		Registry: registry,
		BuildInfo: infrahttp.BuildInfo{
			Service:   cfg.ServiceName,
			Version:   version,
			Commit:    cfg.Commit,
			BuildTime: cfg.BuildTime,
		},
	})

	srv := &http.Server{
		Addr:         ":" + cfg.Port,
		Handler:      router,
		ReadTimeout:  15 * time.Second,
		WriteTimeout: 15 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	runner := shutdown.New(log)
	runner.Register(func(ctx context.Context) error {
		log.Info("shutting down HTTP server")
		return srv.Shutdown(ctx)
	})
	runner.Register(func(ctx context.Context) error {
		return shutdownTracing(ctx)
	})

	log.Info("starting server",
		slog.String("addr", srv.Addr),
		slog.String("env", cfg.Environment),
	)

	go func() {
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Error("server error", slog.Any("error", err))
			os.Exit(1)
		}
	}()

	return runner.ListenAndServe()
}
