#!/usr/bin/env bash
# check_env.sh — Verify required environment variables are set before starting.
# Generated by crux dev.
set -euo pipefail

required=(SERVICE_NAME ENVIRONMENT PORT)

missing=()
for var in "${required[@]}"; do
  if [[ -z "${!var:-}" ]]; then
    missing+=("$var")
  fi
done

if [[ ${#missing[@]} -gt 0 ]]; then
  echo "ERROR: missing required environment variables: ${missing[*]}" >&2
  exit 1
fi

echo "Environment check passed for my-service"
