#!/usr/bin/env bash
# restore-db.sh — Restore local database from a named snapshot.
# Generated by crux dev. Replace with real restore logic.
set -euo pipefail

SNAPSHOT_DIR=".db-snapshots"
SNAPSHOT_NAME="${1:-}"

if [[ -z "$SNAPSHOT_NAME" ]]; then
  echo "Usage: $0 <snapshot-name>" >&2
  exit 1
fi

echo "TODO: add restore logic for my-service from $SNAPSHOT_DIR/$SNAPSHOT_NAME"
