// Package logging provides structured JSON logging with OTel trace correlation.
// Generated by crux dev.
package logging

import (
	"github.com/gin-gonic/gin"
	"go.opentelemetry.io/otel/trace"
)

// Middleware extracts trace_id and span_id from the active OTel span and stores
// them as logging Fields. Must be registered after tracing.Middleware.
func Middleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		span := trace.SpanFromContext(c.Request.Context())
		sc := span.SpanContext()

		f := Fields{}
		if sc.HasTraceID() {
			f.TraceID = sc.TraceID().String()
		}
		if sc.HasSpanID() {
			f.SpanID = sc.SpanID().String()
		}

		ctx := ContextWithFields(c.Request.Context(), f)
		c.Request = c.Request.WithContext(ctx)
		c.Next()
	}
}
