// Package http provides the HTTP presentation layer for my-service.
// Generated by crux dev.
package http

import (
	"context"
	"net/http"
	"time"
)

// Server wraps http.Server with sensible production timeouts.
type Server struct {
	inner *http.Server
}

// NewServer returns a Server bound to addr with the given handler.
// Timeouts follow the Tier 1 defaults: 15s read/write, 60s idle.
func NewServer(addr string, handler http.Handler) *Server {
	return &Server{
		inner: &http.Server{
			Addr:         addr,
			Handler:      handler,
			ReadTimeout:  15 * time.Second,
			WriteTimeout: 15 * time.Second,
			IdleTimeout:  60 * time.Second,
		},
	}
}

// ListenAndServe starts the HTTP server. It returns http.ErrServerClosed on
// graceful shutdown.
func (s *Server) ListenAndServe() error {
	return s.inner.ListenAndServe()
}

// Shutdown gracefully drains active connections within the given context deadline.
func (s *Server) Shutdown(ctx context.Context) error {
	return s.inner.Shutdown(ctx)
}
